In [1]:
import pandas as pd
df= pd.read_csv('boundary_corelation.csv')
from sklearn.cluster import DBSCAN

import numpy as np
import time

In [2]:
df.head(5)

0      1      2      3      4      5      6      7      8      9  ...  \
0  0.000  0.835  0.585  0.416  1.000  0.936  1.000  0.939  0.413  1.000  ...   
1  0.835  0.000  0.411  0.622  0.338  0.151  0.357  0.190  0.748  1.000  ...   
2  0.585  0.411  0.000  0.372  0.589  0.506  0.601  0.529  0.497  1.000  ...   
3  0.416  0.622  0.372  0.000  0.793  0.719  0.798  0.732  0.182  1.000  ...   
4  1.000  0.338  0.589  0.793  0.000  0.325  0.028  0.311  0.917  0.845  ...   

      53     54     55     56     57     58     59     60     61     62  
0  0.763  0.388  0.546  1.000  0.847  0.941  1.000  0.183  0.374  0.330  
1  0.867  0.868  0.902  0.368  0.136  0.214  0.694  0.865  0.865  0.855  
2  0.758  0.669  0.754  0.608  0.457  0.512  0.580  0.661  0.661  0.637  
3  0.762  0.534  0.654  0.802  0.651  0.740  0.846  0.523  0.522  0.489  
4  1.000  1.000  1.000  0.045  0.390  0.331  0.701  1.000  0.963  1.000  

[5 rows x 63 columns]

In [3]:
df_new=pd.DataFrame()
# df_new['pathid']=df.index+1 ##make the id starting from 1 rather than default 0
df_new['pathid']=df.index+1

df_new['pathid']=df_new['pathid'].replace([63],['Clusters_found'])
df_new = df_new.append({'pathid':'Noise_count'},ignore_index=True)

In [4]:
# df_new=df_new.drop(62)
df_new.tail(5)

pathid
59              60
60              61
61              62
62  Clusters_found
63     Noise_count

In [5]:
# epsilons= [0.25]
# min_support=[4]
# print("############# DBSCAN #############")
# start_time = time.time()
# for eps in epsilons:
#     print("========== Epsilon =", eps,"==========")
#     for mins in min_support:
#         df= pd.read_csv('boundary_corelation.csv')
#         ##drop the index 62 for both column and row as the last path is not needed
#         df=df.drop('62',axis=1,inplace=False)
#         df=df.drop(62)
#         ##run DBSCAN 
#         db= DBSCAN(eps=eps, min_samples=mins, metric="precomputed").fit(df)
#         labels=db.labels_
#         labelx=labels
        
#         ##print the result of DBSCAN
#         print(labels[0::])
#         print("===============================")
#         ##print the minimun support used in the set
#         print('Minimun support:',mins)
#         ##print the total number of clusters (including noise : -1)
#         cluster=np.unique(labels)
#         num_cluster=len(cluster)-1
#         modified_clusters = np.delete(labels, np.where(labels == -1))
#         frequency=np.array(np.unique(modified_clusters, return_counts=True)).T
#         print('Identified clusters:',(len(cluster)-1),"=>\n",frequency)
#         ##create a new row with the Eps and minsuppor used ex: label_0.2_3 (Eps:0.2, Minsupport:3)
#         name= 'label_'+ str(eps)+'_'+str(mins)
#         ##counting the noise number in each set
#         noise= list(labels).count(-1)
#         labels=np.append(labels,num_cluster)
#         labels=np.append(labels,noise)
#         df_new[name]=labels
#         print("Identifide noise",noise)
#         print("===============================\n")
# end_time = time.time()
# print("time take =", end_time - start_time)

In [6]:
epsilons= [0.2,0.25,0.3,0.35,0.4,0.45]
min_support=[2,3,4]
print("############# DBSCAN #############")
start_time = time.time()
for eps in epsilons:
    print("========== Epsilon =", eps,"==========")
    for mins in min_support:
        df= pd.read_csv('boundary_corelation.csv')
        ##drop the index 62 for both column and row as the last path is not needed
        df=df.drop('62',axis=1,inplace=False)
        df=df.drop(62)
        ##run DBSCAN 
        db= DBSCAN(eps=eps, min_samples=mins, metric="precomputed").fit(df)
        labels=db.labels_
        labelx=labels
        
        ##print the result of DBSCAN
        print(labels[0::])
        print("===============================")
        ##print the minimun support used in the set
        print('Minimun support:',mins)
        ##print the total number of clusters (including noise : -1)
        cluster=np.unique(labels)
        num_cluster=len(cluster)-1
        modified_clusters = np.delete(labels, np.where(labels == -1))
        frequency=np.array(np.unique(modified_clusters, return_counts=True)).T
        print('Identified clusters:',(len(cluster)-1),"=>\n",frequency)
        ##create a new row with the Eps and minsuppor used ex: label_0.2_3 (Eps:0.2, Minsupport:3)
        name= 'label_'+ str(eps)+'_'+str(mins)
        ##counting the noise number in each set
        noise= list(labels).count(-1)
        labels=np.append(labels,num_cluster)
        labels=np.append(labels,noise)
        df_new[name]=labels
        print("Identifide noise",noise)
        print("===============================\n")
end_time = time.time()
print("time take =", end_time - start_time)

############# DBSCAN #############
========== Epsilon = 0.2 ==========
[ 0  1  2  3  4  1  4  1  3  5  0  0 -1  4  4  1  1  2 -1 -1 -1  3  6  7
 -1 -1  0  0  0 -1  8 -1  5  4  9 -1  9  1 -1  2  2 -1 10 10 -1  6  3 -1
  3  0 -1 -1  8 -1  7 -1  4  1  1 -1  0 -1]
Minimun support: 2
Identified clusters: 11 =>
 [[ 0  8]
 [ 1  8]
 [ 2  4]
 [ 3  5]
 [ 4  6]
 [ 5  2]
 [ 6  2]
 [ 7  2]
 [ 8  2]
 [ 9  2]
 [10  2]]
Identifide noise 19

[ 0  1  2  3  4  1  4  1  3 -1  0  0 -1  4  4  1  1  2 -1 -1 -1  3 -1 -1
 -1 -1  0  0  0 -1 -1 -1 -1  4 -1 -1 -1  1 -1  2  2 -1 -1 -1 -1 -1  3 -1
  3  0 -1 -1 -1 -1 -1 -1  4  1  1 -1  0 -1]
Minimun support: 3
Identified clusters: 5 =>
 [[0 8]
 [1 8]
 [2 4]
 [3 5]
 [4 6]]
Identifide noise 31

[ 0  1  2  3  4  1  4  1  3 -1  0  0 -1  4  4  1  1  2 -1 -1 -1  3 -1 -1
 -1 -1  0  0  0 -1 -1 -1 -1  4 -1 -1 -1  1 -1  2  2 -1 -1 -1 -1 -1  3 -1
 -1  0 -1 -1 -1 -1 -1 -1  4  1  1 -1  0 -1]
Minimun support: 4
Identified clusters: 5 =>
 [[0 8]
 [1 8]
 [2 4]
 [3 4]
 [4 6]]
Identi

In [7]:
df_new.tail(5)

pathid  label_0.2_2  label_0.2_3  label_0.2_4  label_0.25_2  \
59              60           -1           -1           -1            -1   
60              61            0            0            0             0   
61              62           -1           -1           -1            -1   
62  Clusters_found           11            5            5            10   
63     Noise_count           19           31           32            18   

    label_0.25_3  label_0.25_4  label_0.3_2  label_0.3_3  label_0.3_4  \
59            -1            -1           -1           -1           -1   
60             0             0            0            0            0   
61            -1            -1            0            0            0   
62             5             5            6            5            3   
63            28            28           11           13           20   

    label_0.35_2  label_0.35_3  label_0.35_4  label_0.4_2  label_0.4_3  \
59            -1            -1            -1           -1           -1   
60             0             0             0            0            0   
61             0             0             0            0            0   
62             3             3             2            2            2   
63             8             8            12            7            7   

    label_0.4_4  label_0.45_2  label_0.45_3  label_0.45_4  
59           -1            -1            -1            -1  
60            0             0             0             0  
61            0             0             0             0  
62            1             2             2             1  
63           10             7             7            10

In [8]:
df_new.to_csv('total_DBSCAN_output.csv')

## <font color=blue>update the boundary path cts.csv file.</font>

In [10]:
df_updated= pd.read_csv('boundary_path_cts.csv')
df_updated.head(5)

path  count  proportion  \
0  [1042310505, 1050510634, 1063410589, 105891057...    455    0.290921   
1  [1042310570, 1057010615, 1061510755, 107551061...    308    0.196931   
2  [1042310505, 1050510634, 1063410589, 105891057...    247    0.157928   
3  [1042310505, 1050510634, 1063410589, 105891073...    171    0.109335   
4  [1042310505, 1050510634, 1063410589, 105891057...    128    0.081841   

  path id  label_0.35_2  label_0.35_3  label_0.35_4  label_0.4_2  label_0.4_3  \
0      p1             0             0             0            0            0   
1      p2             1             1             1            1            1   
2      p3             0             0             0            0            0   
3      p4             0             0             0            0            0   
4      p5             1             1             1            1            1   

   label_0.4_4  label_0.45_2  label_0.45_3  label_0.45_4  label_0.5_2  \
0            0             0             0             0            0   
1            1             0             0             0            0   
2            0             0             0             0            0   
3            0             0             0             0            0   
4            1             0             0             0            0   

   label_0.5_3  label_0.5_4  
0            0            0  
1            0            0  
2            0            0  
3            0            0  
4            0            0

In [11]:
name_contains = 'label_'
drop_lst = [col for col in (df_updated.columns) if col.startswith(name_contains)]
df_updated = df_updated.drop(drop_lst, axis=1)
df_updated.head(2)

path  count  proportion  \
0  [1042310505, 1050510634, 1063410589, 105891057...    455    0.290921   
1  [1042310570, 1057010615, 1061510755, 107551061...    308    0.196931   

  path id  
0      p1  
1      p2

In [14]:
epsilons= [0.2,0.25,0.3,0.35,0.4,0.45]
min_support=[2,3,4]
start_time = time.time()
for eps in epsilons:
    for mins in min_support:
        df= pd.read_csv('boundary_corelation.csv')
        ##drop the index 62 for both column and row as the last path is not needed
        df=df.drop('62',axis=1,inplace=False)
        df=df.drop(62)
        ##run DBSCAN 
        db= DBSCAN(eps=eps, min_samples=mins, metric="precomputed").fit(df)
        labels=db.labels_
        labelx=labels
        
        ##create a new row with the Eps and minsuppor used ex: label_0.2_3 (Eps:0.2, Minsupport:3)
        name= 'label_'+ str(eps)+'_'+str(mins)
        ##counting the noise number in each set
        df_updated[name]=labels

end_time = time.time()
print("time taken =", end_time - start_time)
df_updated
df_updated.to_csv('first_step_DBSCAN.csv')##this is the output from DBSCAN combined with path frequency

time taken = 0.10868310928344727
