In [30]:
# conda install -c conda-forge hdbscan
# pip3 install hdbscan
# pip3 install joblib==1.1.0 ##otherwise, error occurs:__init__() got an unexpected keyword argument 'cachedir'
import pandas as pd
df= pd.read_csv('boundary_corelation.csv')## import the correlation matrix
import numpy as np
from sklearn.cluster import KMeans
import time

In [31]:
import hdbscan
from sklearn.datasets import make_blobs
import numpy as np
import time

In [32]:
df_new=pd.DataFrame()
df_new['pathid']=df.index+1
df_new['pathid']=df_new['pathid'].replace([63],['Clusters_found'])
df_new = df_new.append({'pathid':'Noise_count'},ignore_index=True)

In [33]:
df_new.tail(5)

pathid
59              60
60              61
61              62
62  Clusters_found
63     Noise_count

In [34]:
min_cluster_size=[2,3,4,5,6,8,10]
start_time = time.time()
print("========== HDBSCAN ==========")
for mins in min_cluster_size:
    df= pd.read_csv('boundary_corelation.csv')
    ##drop the index 62 for both column and row as the last path is not needed
    df=df.drop('62',axis=1,inplace=False)
    df=df.drop(62)
    ##run HDBSCAN 
    db= hdbscan.HDBSCAN(min_cluster_size=mins).fit(df)
    labels=db.labels_
    labelx=labels

    ##print the result of HDBSCAN
    print(labels[0::])
    print("===============================")
    print('Minimun cluster size:',mins)
    #print the total number of clusters (including noise : -1)
    cluster=np.unique(labels)
    num_cluster=len(cluster)-1
    modified_clusters = np.delete(labels, np.where(labels == -1))
    frequency=np.array(np.unique(modified_clusters, return_counts=True)).T
    print('Identified clusters:',(len(cluster)-1),"=>\n",frequency)
    name= 'label_'+str(mins)
    ##counting the noise number in each set
    noise= list(labels).count(-1)
    labels=np.append(labels,num_cluster)
    labels=np.append(labels,noise)
    df_new[name]=labels
    print("Identifide noise",noise)
    print("===============================\n")
end_time = time.time()
print("time take =", end_time - start_time)

========== HDBSCAN ==========
[ 7  4  5  6  3  4  3  4  6  0  7  7  0  3  3  4  4  5  5 -1  2  6 -1  8
 -1  8  7 -1  7  1  1 -1  0  3  3 -1  3  4  5  5  5 -1 -1  2  2 -1 -1 -1
 -1  7 -1 -1  1 -1  8 -1  3  4  4 -1  7  8]
Minimun cluster size: 2
Identified clusters: 9 =>
 [[0 3]
 [1 3]
 [2 3]
 [3 8]
 [4 8]
 [5 6]
 [6 3]
 [7 7]
 [8 4]]
Identifide noise 17

[ 3  1  2  4  0  1  0  1  4 -1  3  3 -1  0  0  1  1  2  2 -1 -1  4 -1  3
  3  3  3  3  3 -1 -1 -1 -1  0  0 -1  0  1  2  2 -1 -1 -1 -1 -1 -1 -1 -1
  4  3 -1 -1 -1 -1  3  3  0  1  1 -1  3  3]
Minimun cluster size: 3
Identified clusters: 5 =>
 [[ 0  8]
 [ 1  8]
 [ 2  5]
 [ 3 14]
 [ 4  4]]
Identifide noise 23

[ 2  0  3 -1  1  0  1  0  3 -1  2  2 -1  1  1  0  0  3  3 -1 -1  3 -1  2
  2  2  2  2  2 -1 -1 -1 -1  1  1 -1  1  0  3  3  3 -1 -1 -1 -1 -1 -1 -1
  2  2 -1 -1 -1 -1  2 -1  1  0  0 -1  2  2]
Minimun cluster size: 4
Identified clusters: 4 =>
 [[ 0  8]
 [ 1  8]
 [ 2 14]
 [ 3  8]]
Identifide noise 24

[ 2  0  3  3  1  0  1  0 -1 -1  2  2 

In [35]:
df_new.to_csv('total_HDBSCAN.csv')

In [38]:
df= pd.read_csv('boundary_corelation.csv')## import the correlation matrix
df_new=pd.DataFrame()
df_new['pathid']=df.index+1
df_new['pathid']=df_new['pathid'].replace([63],['Clusters_found'])

In [39]:
df_new.tail(5)

pathid
58              59
59              60
60              61
61              62
62  Clusters_found

In [40]:
num_clusters=[3,4,5]
start_time = time.time()
print("========== KMeans ==========")
for num in num_clusters:
    df= pd.read_csv('boundary_corelation.csv')
    ##drop the index 62 for both column and row as the last path is not needed
    df=df.drop('62',axis=1,inplace=False)
    df=df.drop(62)
    ##run Kmeans 
    db= KMeans(n_clusters=num, random_state=0).fit(df)
    labels=db.labels_
    labelx=labels

    ##print the result of Kmeans
    print(labels[0::])
    print("===============================")
    #print the minimun support used in the set
    print('Number of clusters:',num)
    #print the total number of clusters (including noise : -1)
    cluster=np.unique(labels)
    num_cluster=len(cluster)-1
    modified_clusters = np.delete(labels, np.where(labels == -1))
    frequency=np.array(np.unique(modified_clusters, return_counts=True)).T
    print('Identified clusters:',(len(cluster)-1),"=>\n",frequency)
    name= 'label_'+str(num)
    labels=np.append(labels,num_cluster)
    df_new[name]=labels
    print("===============================\n")
end_time = time.time()

========== KMeans ==========
[2 1 0 2 1 1 1 1 2 0 2 2 0 1 1 1 1 0 0 0 1 2 0 2 2 2 2 2 2 1 1 0 0 1 1 0 1
 1 0 0 0 0 1 1 1 0 0 0 2 2 2 2 1 0 2 2 1 1 1 0 2 2]
Number of clusters: 3
Identified clusters: 2 =>
 [[ 0 19]
 [ 1 23]
 [ 2 20]]

[0 1 3 3 1 1 1 1 0 2 0 0 2 1 1 1 1 3 3 2 1 3 3 0 0 0 0 0 0 1 1 2 2 1 1 2 1
 1 3 3 3 2 1 1 1 3 3 3 0 0 0 0 1 2 0 0 1 1 1 2 0 0]
Number of clusters: 4
Identified clusters: 3 =>
 [[ 0 18]
 [ 1 23]
 [ 2  9]
 [ 3 12]]

[1 0 2 2 0 0 0 0 1 3 1 1 3 0 0 0 0 2 2 4 4 2 2 1 1 1 1 1 1 4 4 3 3 0 0 4 0
 0 2 2 2 2 4 4 4 2 2 2 1 1 1 1 4 2 1 1 0 0 0 4 1 1]
Number of clusters: 5
Identified clusters: 4 =>
 [[ 0 16]
 [ 1 18]
 [ 2 14]
 [ 3  4]
 [ 4 10]]



In [41]:
df_new.to_csv('total_KMeans_output.csv')